# Dockerfile.api
FROM php:8.3-apache

# Ensure all packages are updated to the latest security patches
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./ /var/www/html

# instalando os módulos necessários
RUN a2enmod rewrite
RUN a2enmod headers
RUN docker-php-ext-install pdo_mysql

# Instalando a extensão PDO para PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo_pgsql

# instalando a extensão PHP Redis
RUN pecl install redis && docker-php-ext-enable redis

# instalando a extensão PHP Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Configurando o php.ini para aumentar o tamanho máximo de upload e POST
RUN echo "upload_max_filesize = 1G" >> /usr/local/etc/php/php.ini
RUN echo "post_max_size = 1G" >> /usr/local/etc/php/php.ini
RUN echo "memory_limit = 1G" >> /usr/local/etc/php/php.ini

# Configurando o Xdebug
RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.mode=debug,develop" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.client_port=9003" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.log=/var/log/xdebug.log" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.log_level=7" >> /usr/local/etc/php/php.ini

# Configurando o diretório para salvar os arquivos de perfil
RUN mkdir -p /var/log/xdebug
RUN echo "xdebug.output_dir=/var/log/xdebug" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.profiler_output_name=callgrind.out.%t" >> /usr/local/etc/php/php.ini
RUN echo "xdebug.profiler_enable_trigger=1" >> /usr/local/etc/php/php.ini

# Criando o diretório de sessões e configurando permissões
RUN mkdir -p /var/lib/php/sessions
RUN chown -R www-data:www-data /var/lib/php/sessions
RUN echo "session.save_path = /var/lib/php/sessions" >> /usr/local/etc/php/php.ini

RUN service apache2 restart

EXPOSE 80
